mssql:
  image: docker-all.artifactory.fiks.ks.no/fiks-mssql
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Test1234!
    - DB_NAME=Fiks_test

eventstore:
  image: eventstore/eventstore
  environment:
    - EVENTSTORE_RUN_PROJECTIONS=All
    - EVENTSTORE_START_STANDARD_PROJECTIONS=True