version: '3'
services:

  eventstore:
    image: eventstore/eventstore:release-5.0.8
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
    ports:
      - 1113:1113