version: '3'
services:
  mssql:
    image: docker-all.artifactory.fiks.ks.no/fiks-mssql-2022:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234!
      - DB_NAME=kesdemo
    ports:
      - 1433

  eventstore:
    image: eventstore/eventstore:24.10.6-bookworm-slim
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113"
      - "2113"